### ISSUE TITLE
create ts module docstrings

### ISSUE THREAD

**Issue by aphexlog** [Elevator-Robot/blip#11]

**Comment by johnweland** [comment]
@aphexlog do you mean JSDoc style doc-blocks? 


https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

**Comment by aphexlog** [comment]
Yep and don't forget to bump the version

**Comment by antch57** [comment]
I think we should use TSDoc. https://tsdoc.org/

It's microsofts "proposed" typescript convention for doc comments.
